<?php
$config['use_page_numbers']=TRUE;
$config['page_query_string']=TRUE;
$config['full_tag_open']='<ul>';
$config['full_tag_close']='</ul>';
$config['num_tag_open']='<li>';
$config['num_tag_close']='</li>';
$config['cur_tag_open']='<li class="active"><a href="#">';
$config['cur_tag_close']='</a></li>';
$config['first_link']='&lt;&lt;';
$config['last_link']='&gt;&gt;';
$config['first_tag_open']='<li>';
$config['first_tag_close']='</li>';
$config['last_tag_open']='<li>';
$config['last_tag_close']='</li>';
$config['prev_tag_open']='<li>';
$config['prev_tag_close']='</li>';
$config['next_tag_open']='<li>';
$config['next_tag_close']='</li>';
$config['query_string_segment']='page';
$config['per_page']=B_PER_PAGE;
?>
